### ISSUE TITLE
* (1) Optimizer Discrepancy + Reflexion Analysis + Use Case Diagram

### ISSUE THREAD

**Issue by Derevi** [Derevi/breakfast-club-as2#16]
Make a proposal of the reflexion analysis you want to analyze here..
You will likely need to examine the functional calls + control flow here (use a script), in order to properly justify the existence of the discrepancy

**Comment by kanz-creation** [comment]
i shall also contribute here

**Comment by kanz-creation** [comment]
![image](https://user-images.githubusercontent.com/46408189/140630966-c5eb2a1d-12ec-4515-9c91-3511996b6a2c.png)

This is a dependency I found. This was found under 
https://github.com/postgres/postgres/blob/master/src/backend/optimizer/prep/prepjointree.c

Basically the optimizer I think has some sort of dependency on parser to formulate an input. 
Interesting to look into! 
Tell me if you wanna continue our investigation on this.

**Comment by Derevi** [comment]
copied and pasted:
- be careful of examining dependencies to the Plan subsystem, since it contains planner.c which is the holds the interface/api used by external systems
Maybe this will be helpful for you.
- try to pick discrepancy that has a recent commit log, usually this implies a quick fix, and maybe an unintended dependency
  - Usually you can check the blame of where the header file is included, and follow it to past commits untill you get to a point where it was never loaded in.  as an example, the one i am working on goes as far back as 13 months only.
  - its also possible it was a hack from way back and left there, but then that is a little harder to justify or reason about i guess. Either way its up to you.
