### ISSUE TITLE
* (3) Optimizer Discrepancy + Reflexion Analysis + Use Case Diagram

### ISSUE THREAD

**Issue by Derevi** [Derevi/breakfast-club-as2#18]
Make a proposal of the reflexion analysis you want to analyze here..
You will likely need to examine the functional calls + control flow here (use a script), in order to properly justify the existence of the discrepancy

**Comment by Derevi** [comment]
we will be examining planning and tcop dependencies

**Comment by Derevi** [comment]
Dependency between optimizer utils and rewriter..

**Comment by t1shfiq** [comment]
@Derevi  please check this doc: https://docs.google.com/document/d/14EXeReZBR6O47QnoF-DVg28LGVhR9nCZrRCwbvG3_Ns/edit
